url: https://buzeto.com
baseurl: 

# Site settings
title: Buzeto Technology
email: me@buzeto.com
description: "Buzeto Technology is a company that holds the endeavours of Fabricio Buzeto a.k.a Fabs. Coder, Researcher and Entrepreneur, working with big corporations and smaall startups Fabs purpose in life is to do great stuf with software. With this goal in mind he helps startups and companies to build and improve their teams both in the technical and cultural spheres."
logo: logo

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Fabricio Buzeto
  pic: fabs
  position: Software Engineer
  social:
    - title: twitter
      url: https://twitter.com/nukdf
    - title: linkedin
      url: https://br.linkedin.com/in/fabriciobuzeto
    - title: user
      url: http://about.buzeto.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/buzetotech
  - title: stack-overflow
    url: http://stackoverflow.com/users/673086/fabricio-buzeto
  - title: github
    url: https://github.com/nuk

# Postal address (add as many lines as necessary)
address:
  - line: South Lake
  - line: Brazilia, Brazil

# Build settings
markdown: kramdown
permalink: pretty